version: "3.7"

services:
  db:
    image: postgres:10-alpine # "bitnami/postgresql:10"
    container_name: stskp_api_db
    volumes:
      - backend-db-volume:/var/lib/postgresql/data
    environment:
     - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  backend-db-volume:
    name: db-volume
