version: '3' # https://taskfile.dev/#/usage

tasks:
  lint: golangci-lint run

  resolve-go-mod: go mod tidy

  up:
    dir: docker
    cmds:
      - docker-compose up -d

  down:
    dir: docker
    cmds:
      - docker-compose down

  build: go build -v

  test: go test ./...
